scan_filter_chain:
  ros__parameters:
    filter1:
      name: angle_filter
      type: laser_filters/LaserScanAngularBoundsFilter
      params:
        lower_angle: -0.7854  # -90 degrees in radians
        upper_angle: 0.7854   # 90 degrees in radians
